services:
  account-pool-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: account-pool-manager
    ports:
      - "3015:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      ADMIN_PASSWORD: "Yy19971215@"
      ADMIN_SESSION_TOKEN: "account-pool-admin-Yy19971215"
    volumes:
      - ./data:/app/data
